source 'https://github.com/CocoaPods/Specs'

platform :ios, '7.0'

inhibit_all_warnings!

target 'Instamaniac' do
    pod 'Analytics/Segmentio'
    pod 'ChameleonFramework'
    pod 'CocoaLumberjack'
    pod 'Crashlytics'
    pod 'CRToast'
    pod 'Fabric'
    pod 'FSInteractiveMap'
    pod 'FSOpenInInstagram'
    pod 'Google-Mobile-Ads-SDK'
    pod 'InstagramKit'
    pod 'IOS-Offline-GeoCoder'
    pod 'JGProgressHUD'
    pod 'OpenSans'
    pod 'Parse'
    pod 'pop'
    pod 'SDWebImage'
    pod 'SimpleAuth/Instagram'
    pod 'UICountingLabel'

    pod 'SimulatorStatusMagic', :configurations => ['Debug']
end