devices([
  "iPhone 6s",
  "iPhone 6s Plus",
  "iPhone 5"
])

languages([
  'en-US'
])

screenshots_path "./screenshots"

clear_previous_screenshots
scheme 'Instamaniac'
custom_build_args "GCC_PREPROCESSOR_DEFINITIONS='$(inherited) SNAPSHOT=1' OTHER_SWIFT_FLAGS='$(inherited) -DSNAPSHOT=1'"
